spring.application.name=Raph-furniture

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/furnitureDB
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true

# Server Configuration
server.port=8081

# Mpesa Daraja Credentials
mpesa.base.url=https://sandbox.safaricom.co.ke
mpesa.consumer.key=ONv2Zi5boHxcpDlTuSZ46z1gDqrLJpGvGu2M62FxUuHsvd8L
mpesa.consumer.secret=wjiyzKoNthfKCaP10aEyV4CvMErtVmfJyZsGQPgkW4X2jAddLvv6HW7zD7ffagHo
mpesa.shortcode=174379
mpesa.passkey=bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919
mpesa.callback.url=https://2d7d9ce4d8ec.ngrok-free.app/api/v1/payment/callback

# Africa's Talking configuration
africastalking.username=sandbox
africastalking.api.key=atsk_e9d4648f201283ed5e568547936dccc24cdb87d4b36f8a28f3c6bf0c03cdd0222b8abfb7